### ISSUE TITLE
[Suggestion] Add aria-label with the name of the theme

### ISSUE THREAD

**Issue by Slddev** [redstonekasi/theme-toggler#10]
This can be useful for editing things using CSS and determining what theme is being selected. Also useful for CSS selectors.

**Comment by redstonekasi** [comment]
I'm not sure if I understand what you want me to do correctly. Do you want me to add an aria-label to the individual theme cards?

**Comment by redstonekasi** [comment]
This plugin has been archived, it should continue to work in the future because Powercord is not updating v2 internals anymore.
