### ISSUE TITLE
Disable new themes by default?

### ISSUE THREAD

**Issue by God-damnit-all** [redstonekasi/theme-toggler#2]
This is a good plugin, but my only complaint is that new themes are enabled by default, creating situations where, if you want to check out multiple themes, they all conflict and break each other to the point you can't actually get to the Theme Toggler tab - not to mention the lag as multiple CSS themes are applied at once.

**Comment by redstonekasi** [comment]
Sorry for the long wait, I currently can't work on this plugin due to issues with my computer.
As far as I know this is normal powercord behaviour, which is why I don't plan on changing it.
