### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RIPzValidTV** [redstonekasi/theme-toggler#3]
I have no idea how to do this, please explain step by step.
I'm new to this

**Comment by Stebulous** [comment]
same ive apparently had it installed for months but it wont load my themes and now im stuck using a theme unless i delete it

**Comment by redstonekasi** [comment]
Go to `User settings -> Theme Toggler` and switch your themes on and off.
You can also use the `.theme [ enable, disable ] [ theme ID ]` command.
If your themes don't load make sure that they are under the `powercord/src/Powercord/themes` folder. You should also check if they are Powercord themes and not for another mod like BetterDiscord.

**Comment by redstonekasi** [comment]
If you still need help go to the [Powercord](https://discord.com/invite/powercord) discord server and ask for help in [#plugin-support](https://discordapp.com/channels/538759280057122817/755004260902764646).
